openapi: 3.0.0
info:
  title: Open Banking Directory API
  version: 2.0.0
  description: OB Tech Directory API
servers:
  - url: https://matls-dirapi.openbanking.org.uk
    description: Production
  - url: https://matls-dirapi.openbankingtest.org.uk
    description: Sandbox
paths:
  '/v2.1/organisation':
    post:
      summary: Enrol a eIDAS QWAC/QSeal-bearing participant
      description: Enrol an eIDAS QWAC/QSealC certificate-bearing participant onto the Open Banking Directory. Currenty only TPPs can use this enrolment endpoint.Enrol an eIDAS QWAC/QSeal certificate-bearing participant onto the Open Banking Directory.
      tags:
        - Organisations v2.1
    get:
      summary: Get all organisations that the client is authorised to retrieve
      description: Note that this was not in the original design but is included to inform the client
      tags:
        - Organisations v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}':
    get:
      summary: Get the given organisation's details
      tags:
        - Organisations v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/contact/{ContactType}':
    put:
      summary: Update the business or the technical contacts for the given organisation
      tags:
        - Contacts v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the business or the technical contacts for the given organisation
      x-PingAccessResourceName: OrganisationContactGET
      x-PingAccessRuleType: uk.org.openbanking.policy.RequestHostOverride
      x-PingAccessRuleTarget: obdorgcontacts.{environment}
      tags:
        - Contacts v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/software-statement':
    post:
      summary: Create a software statement
      tags:
        - Software Statements v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get all software statements for the given organisation
      tags:
        - Software Statements v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}':
    get:
      summary: Get a software statement
      tags:
        - Software Statements v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    put:
      summary: Activate or deactive a software statement
      tags:
        - Software Statements v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2.1/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/redirect-uri':
    post:
      summary: Add a redirect URI to the given Software Statement
      tags:
        - Software Statement Redirect URIs v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2.1/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/software-statement-assertion':
    get:
      summary:
        Retrieve the software statement assertion for the given SoftwareStatementID.
      description: |
        # Depending on the type of participant, one of the following pre-conditions must be met in order to generate an SSA:
         * EU TPPs NOT on the TPR  must hold at least one eIDAS certificate.
         * EU TPPs on the TPR must hold at least one eIDAS or OB certiticate.
         * UK TPPs on the TPR must hold at least one OB certificate.
        The response body is a signed JWT and the values found in the header and the payload of the SSA are specified below
        # Terminology
          This specification uses the terms "access token", "authorization code", "authorization endpoint", "authorization grant", "authorization server", "client", "client identifier", "client secret", "grant type", "protected resource", "redirection URI", "refresh token", "resource owner", "resource server", "response type", and "token endpoint" defined by OAuth 2.0 [RFC6749] and uses the term "Claim" defined by JSON Web Token (JWT) [RFC7519].
          * __Account Servicing Payment Services Provider (ASPSP)__ -- An organisation managing customer accounts (and operating banking APIs).
          * __Primary Technical Contact__ -- The person at the TPP who creates an SSA and invokes a registration mechanism. This is an example of an [RFC7591] Client Developer.
          * __OB Organisation ID__ -- The unique identifier for each OpenBanking participant. Both TPPs and ASPSPs have OB Organisation IDs.
          * __OpenBanking Directory__ -- An implementation of a [PSD2] competent authority; acts as an Identity Provider, certificate authority, and registry governing the participants in the UK OpenBanking API scheme.
          * __ASPSP Registration Endpoint__ -- OAuth 2.0 & [RFC7591] compliant endpoint, exact value is discoverable from the [OIDCD] openid-configuration file of the ASPSP.
          * __Software Statement Assertion (SSA)__ -- An implementation of an [RFC7591] software statement, signed by the OpenBanking Directory.
          * __Trusted Third Party (TPP)__ -- An organization working to initiate payments or consume account information with/from an ASPSP.
          * __TPP Client Software__ -- software implementing an OAuth2 client, interacting with an ASPSP registration endpoint.
        # Software Statement Assertion (SSA)
          The SSA is a JSON Web Token (JWT) containing client metadata about an instance of TPP client software. The JWT is issued and signed by the OpenBanking Directory.
        ## SSA Payload
          The payload of an OpenBanking SSA MUST be a compliant software statement according to [RFC7591]. The SSA MUST also be a compliant JWT according to [RFC7519]. The following metadata profiles the metadata in [RFC7591] and [RFC7519]:
          | Metadata | Description | Source Specification |
          |----------|-------------|----------------------|
          |`software_id`|Unique Identifier for TPP Client Software|[RFC7591]|
          |`iss`|SSA Issuer|[RFC7519]|
          |`iat`|Time SSA issued|[RFC7519]|
          |`jti`|JWT ID|[RFC7519]|
          The following software metadata is additionally defined for this profile:
          |Metadata |Description |Field Size |Default values |
          |---------|------------|-----------|---------------|
          |`software_client_id`|The Client ID Registered at OB used to access OB resources|Base62 GUID (22 chars)| |
          |`software_client_description`|Human-readable detailed description of the client|Max256Text| |
          |`software_client_name`|Human-readable Software Name|Max40Text| |
          |`software_client_uri`|The website or resource root uri|Max256Text| |
          |`software_version`|The version number of the software should a TPP choose to register and / or maintain it|decimal| |
          |`software_environment`|Requested additional field to avoid certificate check|Max256Text| |
          |`software_jwks_endpoint`|Contains all active signing and network certs for the software|Max256Text| |
          |`software_jwks_revoked_endpoint`|Contains all revoked signing and network certs for the software|Max256Text| |
          |`software_logo_uri`|Link to the TPP logo. Note, ASPSPs are not obliged to display images hosted by third parties|Max256Text| |
          |`software_mode`|ASPSP Requested additional field to indicate that this software is `Test` or `Live` the default is `Live`. Impact and support for `Test` software is up to the ASPSP.|Max40Text| |
          |`software_on_behalf_of_org`|A reference to fourth party organsiation resource on the OB Directory if the registering TPP is acting on behalf of another.|Max40Text| |
          |`software_policy_uri`|A link to the software's policy page|Max256Text| |
          |`software_redirect_uris`|Registered client callback endpoints as registered with Open Banking|A string array of Max256Text items|
          |`software_roles`|A multi value list of PSD2 roles that this software is authorized to perform.|A string array of Max256Text items| |
          |`software_tos_uri`|A link to the software's terms of service page|Max256Text| |
          The following Organisational metadata is defined for this profile:
          |Metadata |Description |Field Size | Default values |
          |---------|------------|-----------|----------------|
          |`organisation_competent_authority_claims`|Authorisations granted to the organsiation by an NCA|CodeList {`AISP`, `PISP`, `CBPII`, `ASPSP`}| |
          |`org_status`|Included to cater for voluntary withdrawal from OB scenarios|`Active`, `Revoked`, or `Withdrawn`| |
          |`org_id`|The Unique TPP or ASPSP ID held by OpenBanking.|Max35Text| |
          |`org_name`|Legal Entity Identifier or other known organisation name|Max140Text| |
          |`org_contacts`|JSON array of objects containing a triplet of name, email, and phone number|Each item Max256Text| |
          |`org_jwks_endpoint`|Contains all active signing and network certs for the organisation|Max256Text| |
          |`org_jwks_revoked_endpoint`|Contains all revoked signing and network certs for the organisation|Max256Text| |
        ## SSA header
          The SSA header MUST comply with [RFC7519].
          |Metadata |Description |Comments |
          |---------|------------|---------|
          |`typ`|MUST be set to `JWT`| |
          |`alg`|MUST be set to `ES256` or `PS256`| |
          |`kid`|The kid will be kept the same as the `x5t` parameter. (X.509 Certificate SHA-1 Thumbprint) of the signing certificate.| |
          ### Example SSA
          The elements defined in the software statement will consist of the following values.
          *Note that there are inconsistent applications of booleans or "Active" strings in the current data model.*
          *Note that there are inconsistent applications of status flags case sensitivity.*
          *The attributes required to be displayed by ASPSPs.*
        ```
        {
          "typ": "JWT",
          "alg": "ES256",
          "kid": "ABCD1234"
        }
        {
          "iss": "OpenBanking Ltd",
          "iat": 1492756331,
          "jti": "id12345685439487678",
          "software_environment": "production",
          "software_mode": "live",
          "software_id": "65d1f27c-4aea-4549-9c21-60e495a7a86f",
          "software_client_id": "OpenBanking TPP Client Unique ID",
          "software_client_name": "Amazon Prime Movies",
          "software_client_description": "Amazon Prime Movies is a moving streaming service",
          "software_version": "2.2",
          "software_client_uri": "https://prime.amazon.com",
          "software_redirect_uris": [
            "https://prime.amazon.com/cb",
            "https://prime.amazon.co.uk/cb"
          ],
          "software_roles": [
            "PISP",
            "AISP"
          ],
          "organisation_competent_authority_claims": {
            "authority_id": "FMA", // Austrian Financial Market Authority
            "registration_id": "111111",
            "status": "Active",
            "authorisations":  [
              {
                "member_state": "GB",
                "roles": [
                  "PISP",
                  "AISP"
                ]
              },
              {
                "member_state": "IR",
                "roles": [
                  "PISP"
                ]
              }
            ]
          },
          "software_logo_uri": "https://prime.amazon.com/logo.png",
          "org_status": "Active",
          "org_id": "Amazon TPPID",
          "org_name": "OpenBanking TPP Registered Name",
          "org_contacts": [
            {
              "name": "contact name",
              "email": "contact@contact.com",
              "phone": "+447890130558"
              "type": "business"
            },
            {
              "name": "contact name",
              "email": "contact@contact.com",
              "phone": "+447890130558",
              "type": "technical"
            }
          ],
          "org_jwks_endpoint": "https://jwks.openbanking.org.uk/org_id/org_id.jkws",
          "org_jwks_revoked_endpoint": "https://jwks.openbanking.org.uk/org_id/revoked/org_id.jkws",
          "software_jwks_endpoint": "https://jwks.openbanking.org.uk/org_id/software_id.jkws",
          "software_jwks_revoked_endpoint": "https://jwks.openbanking.org.uk/org_id/revoked/software_id.jkws",
          "software_policy_uri": "https://tpp.com/policy.html",
          "software_tos_uri": "https://tpp.com/tos.html",
          "software_on_behalf_of_org": "Acme Ltd"
        }
        {
          Signature
        }
        ```
        # Automated Client Registration
        A TPP MAY use automated client registration to submit an SSA to an ASPSP in exchange for client credentials for use as a client against an OAuth 2.0 Authorization Server. It is RECOMMENDED for ASPSPs to support the automated client registration mechanism. A large number of claims that OpenID Connect OPs could support as part of the RFC7591 request are detailed [https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata](https://openid.net/specs/openid-connect-registrati[...]
        ## Request Validation
        Prior to issuing a client registration response, the ASPSP MUST perform the following checks
        * The ASPSP SHOULD check whether the TPP that initiated the TLS connection is the same TPP as listed in the SSA.
        * In the case where a gateway or other piece of infrastructure pre-terminates the MATLS channel in front of the registration endpoint, the certificate used to initiate the connection or some part of that certificate (such as DN & Issuer) SHOULD be made available to the ASPSP for validation against the claims in the SSA.
        * The registration request MUST be signed with a key contained in the JWKS referenced in the SSA included with the request. This ensures that a holder-of-key proof-of-possession is performed proving that the TPP app was the originally intended recipient of the SSA when the OB issued it.
        * The SSA MUST be validated according to [RFC7519], including validation of the signature and validity window.
        JWT signature must be validated, this involves retrieving the jwks keyset for both the OB and the TPP. The OB keystore location will be published as part of the directory specification, The TPP's will be included in the software statement.
        ### SSA Lifetime
        The SSA's Lifetime / Validity period is not defined by Open Banking. ASPSPs in the Open Banking ecosystem are required to implement pragmatic time ranges in which to accept an SSA. For example, an ASPSP that has implemented Dynamic Client Registration may choose to accept SSA's that were issued no earlier than 1 minute prior to their presentation however ASPSPs that only support manual registration may need to accept SSAs that were issued 30 minutes prior as the elapsed time period betwe[...]
      tags:
        - Software Statement Assertions v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/certificate':
    get:
      summary: Get the certificates for the given organisation
      tags:
        - Organisation Certificates v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/certificate/{OrganisationCertificateType}':
    post:
      summary: Store or create a new certificate of the given OrganisationCertificateType for the given organisation
      tags:
        - Organisation Certificates v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificates of the given OrganisationCertificateType for the given oranisation
      tags:
        - Organisation Certificates v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/certificate/kid/{CertificateOrKeyId}':
    get:
      summary: Retrieve a certificate with the given CertificateOrKeyId
      tags:
        - Organisation Certificates v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    delete:
      summary: Revoke or remove a certificate with the given CertificateOrKeyId
      tags:
        - Organisation Certificates v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2.1/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate':
    get:
      summary: Get certificates for the given software statement
      tags:
        - Software Statement Certificates v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate/{SoftwareStatementCertificateOrKeyType}':
    post:
      summary: Add a key or create a new certificate for the given software statement
      tags:
        - Software Statement Certificates v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificates of the given type for the given software statement
      tags:
        - Software Statement Certificates v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate/{OrganisationAssociativeCertificateType}/{CertificateOrKeyId}':
    put:
      summary: Associate/de-associate a QSEAL/OBSEAL certificate with the given software statement
      tags:
        - Certificate Associations v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificate of the given type and ID for the given software statement
      tags:
        - Software Statement Certificates v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2.1/organisation/{OrganisationId}/authorisation-server':
    get:
      summary: Get all Authorisation Servers for the given organisation
      tags:
        - Authorisation Servers v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    post:
      summary: Create an Authorisation Server for the given organisation
      tags:
        - Authorisation Servers v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2.1/organisation/{OrganisationId}/authorisation-server/{AuthorisationServerId}':
    get:
      summary: Get .well-known entity
      tags:
        - Authorisation Servers v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    put:
      summary: Update .well-known entity
      tags:
        - Authorisation Servers v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    delete:
      summary: Delete an Authorisation Server
      tags:
        - Authorisation Servers v2.1
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2.1/certificate/validate':
    post:
      summary: Validate certificate
      tags:
        - Certificate Validation v2.1
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation':
    post:
      summary: Enrol a eIDAS QWAC/QSeal-bearing participant
      description: Enrol an eIDAS QWAC/QSealC certificate-bearing participant onto the Open Banking Directory. Currenty only TPPs can use this enrolment endpoint.Enrol an eIDAS QWAC/QSeal certificate-bearing participant onto the Open Banking Directory.
      tags:
        - Organisations
    get:
      summary: Get all organisations that the client is authorised to retrieve
      description: Note that this was not in the original design but is included to inform the client
      tags:
        - Organisations
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}':
    get:
      summary: Get the given organisation's details
      tags:
        - Organisations
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/contact/{ContactType}':
    put:
      summary: Update the business or the technical contacts for the given organisation
      tags:
        - Contacts
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the business or the technical contacts for the given organisation
      x-PingAccessResourceName: OrganisationContactGET
      x-PingAccessRuleType: uk.org.openbanking.policy.RequestHostOverride
      x-PingAccessRuleTarget: obdorgcontacts.{environment}
      tags:
        - Contacts
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/software-statement':
    post:
      summary: Create a software statement
      tags:
        - Software Statements
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get all software statements for the given organisation
      tags:
        - Software Statements
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}':
    get:
      summary: Get a software statement
      tags:
        - Software Statements
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    put:
      summary: Activate or deactive a software statement
      tags:
        - Software Statements
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/redirect-uri':
    post:
      summary: Add a redirect URI to the given Software Statement
      tags:
        - Software Statement Redirect URIs
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/software-statement-assertion':
    get:
      summary:
        Retrieve the software statement assertion for the given SoftwareStatementID.
      description: |
        # Depending on the type of participant, one of the following pre-conditions must be met in order to generate an SSA:
         * EU TPPs NOT on the TPR  must hold at least one eIDAS certificate.
         * EU TPPs on the TPR must hold at least one eIDAS or OB certiticate.
         * UK TPPs on the TPR must hold at least one OB certificate.
        The response body is a signed JWT and the values found in the header and the payload of the SSA are specified below
        # Terminology
          This specification uses the terms "access token", "authorization code", "authorization endpoint", "authorization grant", "authorization server", "client", "client identifier", "client secret", "grant type", "protected resource", "redirection URI", "refresh token", "resource owner", "resource server", "response type", and "token endpoint" defined by OAuth 2.0 [RFC6749] and uses the term "Claim" defined by JSON Web Token (JWT) [RFC7519].
          * __Account Servicing Payment Services Provider (ASPSP)__ -- An organisation managing customer accounts (and operating banking APIs).
          * __Primary Technical Contact__ -- The person at the TPP who creates an SSA and invokes a registration mechanism. This is an example of an [RFC7591] Client Developer.
          * __OB Organisation ID__ -- The unique identifier for each OpenBanking participant. Both TPPs and ASPSPs have OB Organisation IDs.
          * __OpenBanking Directory__ -- An implementation of a [PSD2] competent authority; acts as an Identity Provider, certificate authority, and registry governing the participants in the UK OpenBanking API scheme.
          * __ASPSP Registration Endpoint__ -- OAuth 2.0 & [RFC7591] compliant endpoint, exact value is discoverable from the [OIDCD] openid-configuration file of the ASPSP.
          * __Software Statement Assertion (SSA)__ -- An implementation of an [RFC7591] software statement, signed by the OpenBanking Directory.
          * __Trusted Third Party (TPP)__ -- An organization working to initiate payments or consume account information with/from an ASPSP.
          * __TPP Client Software__ -- software implementing an OAuth2 client, interacting with an ASPSP registration endpoint.
        # Software Statement Assertion (SSA)
          The SSA is a JSON Web Token (JWT) containing client metadata about an instance of TPP client software. The JWT is issued and signed by the OpenBanking Directory.
        ## SSA Payload
          The payload of an OpenBanking SSA MUST be a compliant software statement according to [RFC7591]. The SSA MUST also be a compliant JWT according to [RFC7519]. The following metadata profiles the metadata in [RFC7591] and [RFC7519]:
          | Metadata | Description | Source Specification |
          |----------|-------------|----------------------|
          |`software_id`|Unique Identifier for TPP Client Software|[RFC7591]|
          |`iss`|SSA Issuer|[RFC7519]|
          |`iat`|Time SSA issued|[RFC7519]|
          |`jti`|JWT ID|[RFC7519]|
          The following software metadata is additionally defined for this profile:
          |Metadata |Description |Field Size |Default values |
          |---------|------------|-----------|---------------|
          |`software_client_id`|The Client ID Registered at OB used to access OB resources|Base62 GUID (22 chars)| |
          |`software_client_description`|Human-readable detailed description of the client|Max256Text| |
          |`software_client_name`|Human-readable Software Name|Max40Text| |
          |`software_client_uri`|The website or resource root uri|Max256Text| |
          |`software_version`|The version number of the software should a TPP choose to register and / or maintain it|decimal| |
          |`software_environment`|Requested additional field to avoid certificate check|Max256Text| |
          |`software_jwks_endpoint`|Contains all active signing and network certs for the software|Max256Text| |
          |`software_jwks_revoked_endpoint`|Contains all revoked signing and network certs for the software|Max256Text| |
          |`software_logo_uri`|Link to the TPP logo. Note, ASPSPs are not obliged to display images hosted by third parties|Max256Text| |
          |`software_mode`|ASPSP Requested additional field to indicate that this software is `Test` or `Live` the default is `Live`. Impact and support for `Test` software is up to the ASPSP.|Max40Text| |
          |`software_on_behalf_of_org`|A reference to fourth party organsiation resource on the OB Directory if the registering TPP is acting on behalf of another.|Max40Text| |
          |`software_policy_uri`|A link to the software's policy page|Max256Text| |
          |`software_redirect_uris`|Registered client callback endpoints as registered with Open Banking|A string array of Max256Text items|
          |`software_roles`|A multi value list of PSD2 roles that this software is authorized to perform.|A string array of Max256Text items| |
          |`software_tos_uri`|A link to the software's terms of service page|Max256Text| |
          The following Organisational metadata is defined for this profile:
          |Metadata |Description |Field Size | Default values |
          |---------|------------|-----------|----------------|
          |`organisation_competent_authority_claims`|Authorisations granted to the organsiation by an NCA|CodeList {`AISP`, `PISP`, `CBPII`, `ASPSP`}| |
          |`org_status`|Included to cater for voluntary withdrawal from OB scenarios|`Active`, `Revoked`, or `Withdrawn`| |
          |`org_id`|The Unique TPP or ASPSP ID held by OpenBanking.|Max35Text| |
          |`org_name`|Legal Entity Identifier or other known organisation name|Max140Text| |
          |`org_contacts`|JSON array of objects containing a triplet of name, email, and phone number|Each item Max256Text| |
          |`org_jwks_endpoint`|Contains all active signing and network certs for the organisation|Max256Text| |
          |`org_jwks_revoked_endpoint`|Contains all revoked signing and network certs for the organisation|Max256Text| |
        ## SSA header
          The SSA header MUST comply with [RFC7519].
          |Metadata |Description |Comments |
          |---------|------------|---------|
          |`typ`|MUST be set to `JWT`| |
          |`alg`|MUST be set to `ES256` or `PS256`| |
          |`kid`|The kid will be kept the same as the `x5t` parameter. (X.509 Certificate SHA-1 Thumbprint) of the signing certificate.| |
          ### Example SSA
          The elements defined in the software statement will consist of the following values.
          *Note that there are inconsistent applications of booleans or "Active" strings in the current data model.*
          *Note that there are inconsistent applications of status flags case sensitivity.*
          *The attributes required to be displayed by ASPSPs.*
        ```
        {
          "typ": "JWT",
          "alg": "ES256",
          "kid": "ABCD1234"
        }
        {
          "iss": "OpenBanking Ltd",
          "iat": 1492756331,
          "jti": "id12345685439487678",
          "software_environment": "production",
          "software_mode": "live",
          "software_id": "65d1f27c-4aea-4549-9c21-60e495a7a86f",
          "software_client_id": "OpenBanking TPP Client Unique ID",
          "software_client_name": "Amazon Prime Movies",
          "software_client_description": "Amazon Prime Movies is a moving streaming service",
          "software_version": "2.2",
          "software_client_uri": "https://prime.amazon.com",
          "software_redirect_uris": [
            "https://prime.amazon.com/cb",
            "https://prime.amazon.co.uk/cb"
          ],
          "software_roles": [
            "PISP",
            "AISP"
          ],
          "organisation_competent_authority_claims": {
            "authority_id": "FMA", // Austrian Financial Market Authority
            "registration_id": "111111",
            "status": "Active",
            "authorisations":  [
              {
                "member_state": "GB",
                "roles": [
                  "PISP",
                  "AISP"
                ]
              },
              {
                "member_state": "IR",
                "roles": [
                  "PISP"
                ]
              }
            ]
          },
          "software_logo_uri": "https://prime.amazon.com/logo.png",
          "org_status": "Active",
          "org_id": "Amazon TPPID",
          "org_name": "OpenBanking TPP Registered Name",
          "org_contacts": [
            {
              "name": "contact name",
              "email": "contact@contact.com",
              "phone": "+447890130558"
              "type": "business"
            },
            {
              "name": "contact name",
              "email": "contact@contact.com",
              "phone": "+447890130558",
              "type": "technical"
            }
          ],
          "org_jwks_endpoint": "https://jwks.openbanking.org.uk/org_id/org_id.jkws",
          "org_jwks_revoked_endpoint": "https://jwks.openbanking.org.uk/org_id/revoked/org_id.jkws",
          "software_jwks_endpoint": "https://jwks.openbanking.org.uk/org_id/software_id.jkws",
          "software_jwks_revoked_endpoint": "https://jwks.openbanking.org.uk/org_id/revoked/software_id.jkws",
          "software_policy_uri": "https://tpp.com/policy.html",
          "software_tos_uri": "https://tpp.com/tos.html",
          "software_on_behalf_of_org": "Acme Ltd"
        }
        {
          Signature
        }
        ```
        # Automated Client Registration
        A TPP MAY use automated client registration to submit an SSA to an ASPSP in exchange for client credentials for use as a client against an OAuth 2.0 Authorization Server. It is RECOMMENDED for ASPSPs to support the automated client registration mechanism. A large number of claims that OpenID Connect OPs could support as part of the RFC7591 request are detailed [https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata](https://openid.net/specs/openid-connect-registrati[...]
        ## Request Validation
        Prior to issuing a client registration response, the ASPSP MUST perform the following checks
        * The ASPSP SHOULD check whether the TPP that initiated the TLS connection is the same TPP as listed in the SSA.
        * In the case where a gateway or other piece of infrastructure pre-terminates the MATLS channel in front of the registration endpoint, the certificate used to initiate the connection or some part of that certificate (such as DN & Issuer) SHOULD be made available to the ASPSP for validation against the claims in the SSA.
        * The registration request MUST be signed with a key contained in the JWKS referenced in the SSA included with the request. This ensures that a holder-of-key proof-of-possession is performed proving that the TPP app was the originally intended recipient of the SSA when the OB issued it.
        * The SSA MUST be validated according to [RFC7519], including validation of the signature and validity window.
        JWT signature must be validated, this involves retrieving the jwks keyset for both the OB and the TPP. The OB keystore location will be published as part of the directory specification, The TPP's will be included in the software statement.
        ### SSA Lifetime
        The SSA's Lifetime / Validity period is not defined by Open Banking. ASPSPs in the Open Banking ecosystem are required to implement pragmatic time ranges in which to accept an SSA. For example, an ASPSP that has implemented Dynamic Client Registration may choose to accept SSA's that were issued no earlier than 1 minute prior to their presentation however ASPSPs that only support manual registration may need to accept SSAs that were issued 30 minutes prior as the elapsed time period betwe[...]
      tags:
        - Software Statement Assertions
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/certificate':
    get:
      summary: Get the certificates for the given organisation
      tags:
        - Organisation Certificates
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/certificate/{OrganisationCertificateType}':
    post:
      summary: Store or create a new certificate of the given OrganisationCertificateType for the given organisation
      tags:
        - Organisation Certificates
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificates of the given OrganisationCertificateType for the given oranisation
      tags:
        - Organisation Certificates
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/certificate/kid/{CertificateOrKeyId}':
    get:
      summary: Retrieve a certificate with the given CertificateOrKeyId
      tags:
        - Organisation Certificates
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    delete:
      summary: Revoke or remove a certificate with the given CertificateOrKeyId
      tags:
        - Organisation Certificates
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate':
    get:
      summary: Get certificates for the given software statement
      tags:
        - Software Statement Certificates
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate/{SoftwareStatementCertificateOrKeyType}':
    post:
      summary: Add a key or create a new certificate for the given software statement
      tags:
        - Software Statement Certificates
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificates of the given type for the given software statement
      tags:
        - Software Statement Certificates
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate/{OrganisationAssociativeCertificateType}/{CertificateOrKeyId}':
    put:
      summary: Associate/de-associate a QSEAL/OBSEAL certificate with the given software statement
      tags:
        - Certificate Associations
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificate of the given type and ID for the given software statement
      tags:
        - Software Statement Certificates
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/v2/organisation/{OrganisationId}/authorisation-server':
    get:
      summary: Get all Authorisation Servers for the given organisation
      tags:
        - Authorisation Servers
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    post:
      summary: Create an Authorisation Server for the given organisation
      tags:
        - Authorisation Servers
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2/organisation/{OrganisationId}/authorisation-server/{AuthorisationServerId}':
    get:
      summary: Get .well-known entity
      tags:
        - Authorisation Servers
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    put:
      summary: Update .well-known entity
      tags:
        - Authorisation Servers
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    delete:
      summary: Delete an Authorisation Server
      tags:
        - Authorisation Servers
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/v2/certificate/validate':
    post:
      summary: Validate certificate
      tags:
        - Certificate Validation
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/oauth/{OrganisationId}':
    get:
      summary: Get details of active OAuthClient for the given Organisation
      tags:
        - OAuth Client
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    put:
      summary: Update OAuthClient for the given Organisation
      tags:
        - OAuth Client
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPManage
            - TPPManage
  '/organisation/{OrganisationType}':
    post:
      summary: Enrol a eIDAS QWAC/QSeal-bearing participant
      description: Enrol an eIDAS QWAC/QSeal certificate-bearing participant onto the Open Banking Directory. Currenty only TPPs can use this enrolment endpoint, so please set `OrganisationType` to `tpp`
      tags:
        - Organisations (Legacy)
    get:
      summary: Get all organisations that the client is authorised to retrieve
      description: Note that this was not in the original design but is included to inform the client
      tags:
        - Organisations (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}':
    get:
      summary: Get the given organisation's details
      tags:
        - Organisations (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/contact/{ContactType}':
    put:
      summary: Update the business or the technical contacts for the given organisation
      tags:
        - Contacts (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the business or the technical contacts for the given organisation
      x-PingAccessResourceName: OrganisationContactGET
      x-PingAccessRuleType: uk.org.openbanking.policy.RequestHostOverride
      x-PingAccessRuleTarget: obdorgcontacts.{environment}
      tags:
        - Contacts (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/software-statement':
    post:
      summary: Create a software statement.
      tags:
        - Software Statements (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get all software statements for the given organisation
      tags:
        - Software Statements (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/software-statement/{SoftwareStatementId}':
    get:
      summary: Get a software statement
      tags:
        - Software Statements (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    put:
      summary: Update a software statement
      tags:
        - Software Statements (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/organisation/{OrganisationType}/{OrganisationId}/software-statement/{SoftwareStatementId}/redirect-uri':
    post:
      summary: Add a redirect URI to the given Software Statement
      tags:
        - Software Statement Redirect URIs (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/organisation/{OrganisationType}/{OrganisationId}/software-statement/{SoftwareStatementId}/software-statement-assertion':
    get:
      summary:
        Get a Software Statement Assertion for the given SoftwareStatementID.
      description: |
        The response body is a signed JWT and the values found in the header and the payload of the SSA are specified below
        # Terminology
          This specification uses the terms "access token", "authorization code", "authorization endpoint", "authorization grant", "authorization server", "client", "client identifier", "client secret", "grant type", "protected resource", "redirection URI", "refresh token", "resource owner", "resource server", "response type", and "token endpoint" defined by OAuth 2.0 [RFC6749] and uses the term "Claim" defined by JSON Web Token (JWT) [RFC7519].
          * __Account Servicing Payment Services Provider (ASPSP)__ -- An organisation managing customer accounts (and operating banking APIs).
          * __Primary Technical Contact__ -- The person at the TPP who creates an SSA and invokes a registration mechanism. This is an example of an [RFC7591] Client Developer.
          * __OB Organisation ID__ -- The unique identifier for each OpenBanking participant. Both TPPs and ASPSPs have OB Organisation IDs.
          * __OpenBanking Directory__ -- An implementation of a [PSD2] competent authority; acts as an Identity Provider, certificate authority, and registry governing the participants in the UK OpenBanking API scheme.
          * __ASPSP Registration Endpoint__ -- OAuth 2.0 & [RFC7591] compliant endpoint, exact value is discoverable from the [OIDCD] openid-configuration file of the ASPSP.
          * __Software Statement Assertion (SSA)__ -- An implementation of an [RFC7591] software statement, signed by the OpenBanking Directory.
          * __Trusted Third Party (TPP)__ -- An organization working to initiate payments or consume account information with/from an ASPSP.
          * __TPP Client Software__ -- software implementing an OAuth2 client, interacting with an ASPSP registration endpoint.
        # Software Statement Assertion (SSA)
          The SSA is a JSON Web Token (JWT) containing client metadata about an instance of TPP client software. The JWT is issued and signed by the OpenBanking Directory.
        ## SSA Payload
          The payload of an OpenBanking SSA MUST be a compliant software statement according to [RFC7591]. The SSA MUST also be a compliant JWT according to [RFC7519]. The following metadata profiles the metadata in [RFC7591] and [RFC7519]:
          | Metadata | Description | Source Specification |
          |----------|-------------|----------------------|
          |`software_id`|Unique Identifier for TPP Client Software|[RFC7591]|
          |`iss`|SSA Issuer|[RFC7519]|
          |`iat`|Time SSA issued|[RFC7519]|
          |`jti`|JWT ID|[RFC7519]|
          The following software metadata is additionally defined for this profile:
          |Metadata |Description |Field Size |Default values |
          |---------|------------|-----------|---------------|
          |`software_client_id`|The Client ID Registered at OB used to access OB resources|Base62 GUID (22 chars)| |
          |`software_client_description`|Human-readable detailed description of the client|Max256Text| |
          |`software_client_name`|Human-readable Software Name|Max40Text| |
          |`software_client_uri`|The website or resource root uri|Max256Text| |
          |`software_version`|The version number of the software should a TPP choose to register and / or maintain it|string| |
          |`software_environment`|Requested additional field to avoid certificate check|Max256Text| |
          |`software_jwks_endpoint`|Contains all active signing and network certs for the software|Max256Text| |
          |`software_jwks_revoked_endpoint`|Contains all revoked signing and network certs for the software|Max256Text| |
          |`software_logo_uri`|Link to the TPP logo. Note, ASPSPs are not obliged to display images hosted by third parties|Max256Text| |
          |`software_mode`|ASPSP Requested additional field to indicate that this software is `Test` or `Live` the default is `Live`. Impact and support for `Test` software is up to the ASPSP.|Max40Text| |
          |`software_on_behalf_of_org`|A reference to fourth party organsiation resource on the OB Directory if the registering TPP is acting on behalf of another.|Max40Text| |
          |`software_policy_uri`|A link to the software's policy page|Max256Text| |
          |`software_redirect_uris`|Registered client callback endpoints as registered with Open Banking|A string array of Max256Text items|
          |`software_roles`|A multi value list of PSD2 roles that this software is authorized to perform.|A string array of Max256Text items| |
          |`software_tos_uri`|A link to the software's terms of service page|Max256Text| |
          The following Organisational metadata is defined for this profile:
          |Metadata |Description |Field Size | Default values |
          |---------|------------|-----------|----------------|
          |`organisation_competent_authority_claims`|Authorisations granted to the organsiation by an NCA|CodeList {`AISP`, `PISP`, `CBPII`, `ASPSP`}| |
          |`org_status`|Included to cater for voluntary withdrawal from OB scenarios|`Active`, `Revoked`, or `Withdrawn`| |
          |`org_id`|The Unique TPP or ASPSP ID held by OpenBanking.|Max35Text| |
          |`org_name`|Legal Entity Identifier or other known organisation name|Max140Text| |
          |`org_contacts`|JSON array of objects containing a triplet of name, email, and phone number|Each item Max256Text| |
          |`org_jwks_endpoint`|Contains all active signing and network certs for the organisation|Max256Text| |
          |`org_jwks_revoked_endpoint`|Contains all revoked signing and network certs for the organisation|Max256Text| |
        ## SSA header
          The SSA header MUST comply with [RFC7519].
          |Metadata |Description |Comments |
          |---------|------------|---------|
          |`typ`|MUST be set to `JWT`| |
          |`alg`|MUST be set to `ES256` or `PS256`| |
          |`kid`|The kid will be kept the same as the `x5t` parameter. (X.509 Certificate SHA-1 Thumbprint) of the signing certificate.| |
          ### Example SSA
          The elements defined in the software statement will consist of the following values.
          *Note that there are inconsistent applications of booleans or "Active" strings in the current data model.*
          *Note that there are inconsistent applications of status flags case sensitivity.*
          *The attributes required to be displayed by ASPSPs.*
        ```
        {
          "typ": "JWT",
          "alg": "ES256",
          "kid": "ABCD1234"
        }
        {
          "iss": "OpenBanking Ltd",
          "iat": 1492756331,
          "jti": "id12345685439487678",
          "software_environment": "production",
          "software_mode": "live",
          "software_id": "65d1f27c-4aea-4549-9c21-60e495a7a86f",
          "software_client_id": "OpenBanking TPP Client Unique ID",
          "software_client_name": "Amazon Prime Movies",
          "software_client_description": "Amazon Prime Movies is a moving streaming service",
          "software_version": "2.2",
          "software_client_uri": "https://prime.amazon.com",
          "software_redirect_uris": [
            "https://prime.amazon.com/cb",
            "https://prime.amazon.co.uk/cb"
          ],
          "software_roles": [
            "PISP",
            "AISP"
          ],
          "organisation_competent_authority_claims": {
            "authority_id": "FMA", // Austrian Financial Market Authority
            "registration_id": "111111",
            "status": "Active",
            "authorisations":  [
              {
                "member_state": "GB",
                "roles": [
                  "PISP",
                  "AISP"
                ]
              },
              {
                "member_state": "IR",
                "roles": [
                  "PISP"
                ]
              }
            ]
          },
          "software_logo_uri": "https://prime.amazon.com/logo.png",
          "org_status": "Active",
          "org_id": "Amazon TPPID",
          "org_name": "OpenBanking TPP Registered Name",
          "org_contacts": [
            {
              "name": "contact name",
              "email": "contact@contact.com",
              "phone": "+447890130558"
              "type": "business"
            },
            {
              "name": "contact name",
              "email": "contact@contact.com",
              "phone": "+447890130558",
              "type": "technical"
            }
          ],
          "org_jwks_endpoint": "https://jwks.openbanking.org.uk/org_id/org_id.jkws",
          "org_jwks_revoked_endpoint": "https://jwks.openbanking.org.uk/org_id/revoked/org_id.jkws",
          "software_jwks_endpoint": "https://jwks.openbanking.org.uk/org_id/software_id.jkws",
          "software_jwks_revoked_endpoint": "https://jwks.openbanking.org.uk/org_id/revoked/software_id.jkws",
          "software_policy_uri": "https://tpp.com/policy.html",
          "software_tos_uri": "https://tpp.com/tos.html",
          "software_on_behalf_of_org": "Acme Ltd"
        }
        {
          Signature
        }
        ```
        # Automated Client Registration
        A TPP MAY use automated client registration to submit an SSA to an ASPSP in exchange for client credentials for use as a client against an OAuth 2.0 Authorization Server. It is RECOMMENDED for ASPSPs to support the automated client registration mechanism. A large number of claims that OpenID Connect OPs could support as part of the RFC7591 request are detailed [https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata](https://openid.net/specs/openid-connect-registrati[...]
        ## Request Validation
        Prior to issuing a client registration response, the ASPSP MUST perform the following checks
        * The ASPSP SHOULD check whether the TPP that initiated the TLS connection is the same TPP as listed in the SSA.
        * In the case where a gateway or other piece of infrastructure pre-terminates the MATLS channel in front of the registration endpoint, the certificate used to initiate the connection or some part of that certificate (such as DN & Issuer) SHOULD be made available to the ASPSP for validation against the claims in the SSA.
        * The registration request MUST be signed with a key contained in the JWKS referenced in the SSA included with the request. This ensures that a holder-of-key proof-of-possession is performed proving that the TPP app was the originally intended recipient of the SSA when the OB issued it.
        * The SSA MUST be validated according to [RFC7519], including validation of the signature and validity window.
        JWT signature must be validated, this involves retrieving the jwks keyset for both the OB and the TPP. The OB keystore location will be published as part of the directory specification, The TPP's will be included in the software statement.
        ### SSA Lifetime
        The SSA's Lifetime / Validity period is not defined by Open Banking. ASPSPs in the Open Banking ecosystem are required to implement pragmatic time ranges in which to accept an SSA. For example, an ASPSP that has implemented Dynamic Client Registration may choose to accept SSA's that were issued no earlier than 1 minute prior to their presentation however ASPSPs that only support manual registration may need to accept SSAs that were issued 30 minutes prior as the elapsed time period betwe[...]
      tags:
        - Software Statement Assertions (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/certificate':
    get:
      summary: Get the certificates for the given organisation
      tags:
        - Organisation Certificates (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/certificate/{OrganisationCertificateType}':
    post:
      summary: Store or create a new certificate of the given OrganisationCertificateType for the given organisation
      tags:
        - Organisation Certificates (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificates of the given OrganisationCertificateType for the given oranisation
      tags:
        - Organisation Certificates (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/certificate/kid/{CertificateOrKeyId}':
    get:
      summary: Retrieve a certificate with the given CertificateOrKeyId
      tags:
        - Organisation Certificates (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    delete:
      summary: Revoke or remove a certificate with the given CertificateOrKeyId
      tags:
        - Organisation Certificates (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/organisation/{OrganisationType}/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate':
    get:
      summary: Get certificates for the given software statement
      tags:
        - Software Statement Certificates (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate/{SoftwareStatementCertificateOrKeyType}':
    post:
      summary: Add a key or create a new certificate for the given software statement
      tags:
        - Software Statement Certificates (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificates of the given type for the given software statement
      tags:
        - Software Statement Certificates (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/software-statement/{SoftwareStatementId}/certificate/{OrganisationAssociativeCertificateType}/{CertificateOrKeyId}':
    put:
      summary: Associate/de-associate a QSEAL/OBSEAL certificate with the given software statement
      tags:
        - Certificate Associations (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    get:
      summary: Get the certificate of the given type and ID for the given software statement
      tags:
        - Software Statement Certificates (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
  '/organisation/{OrganisationType}/{OrganisationId}/authorisation-server':
    get:
      summary: Get all Authorisation Servers for the given organisation
      tags:
        - Authorisation Servers (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    post:
      summary: Create an Authorisation Server for the given organisation
      tags:
        - Authorisation Servers (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/organisation/{OrganisationType}/{OrganisationId}/authorisation-server/{AuthorisationServerId}':
    get:
      summary: Get .well-known entity
      tags:
        - Authorisation Servers (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
    put:
      summary: Update .well-known entity
      tags:
        - Authorisation Servers (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
    delete:
      summary: Delete an Authorisation Server
      tags:
        - Authorisation Servers (Legacy)
      security:
        - OAuth2SecurityReadWriteOps:
            - ASPSPReadAccess
            - TPPReadAccess
            - TPPManage
  '/certificate/validate':
    post:
      summary: Validate certificate
      tags:
        - Certificate Validation (Legacy)
      security:
        - OAuth2SecurityReadOps:
            - ASPSPReadAccess
            - TPPReadAccess
components:
  securitySchemes:
    OAuth2SecurityReadOps:
      description: This API uses OAuth 2 with the client credentials grant flow
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://sso.openbanking.me.uk/as/token.oauth2
          scopes:
            TPPReadAccess: Retrieve or Search for Third Party Providers
            ASPSPReadAccess: Read ASPSP Records
    OAuth2SecurityReadWriteOps:
      description: This API uses OAuth 2 with the client credentials grant flow
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://sso.openbanking.me.uk/as/token.oauth2
          scopes:
            TPPReadAccess: Retrieve or Search for Third Party Providers
            TPPManage: Modify Your Third Third Party Provider Record
            ASPSPReadAccess: Read ASPSP Records
            ASPSPManage: Modify ASPSP Records
